#!/bin/bash

NS_LOG="ndn.HelloConsumer:ndn.HelloProducer:ndn.Consumer:ndn.Producer" ./waf --run="$1" 2> hello.log
NS_LOG="ndn.Consumer:ndn.Producer" ./waf --run="$1" 2> app.log
NS_LOG="ndn.WifiNetDeviceTransport:WifiNetDevice" ./waf --run="$1" 2> wifi.log
NS_LOG="YansWifiPhy:YansWifiChannel" ./waf --run="$1" 2> phy.log
NS_LOG="InterferenceHelper" ./waf --run="$1" 2> inf.log