#!/bin/bash

# Define log components
log_components=(
  "caf.StackHelper"
  "caf.Context"

  "ndn.StackHelper"
  "ndn.FibHelper"

  "ndn.Consumer"
  "ndn.Producer"
  "ndn.AlertConsumer"
  "ndn.AlertProducer"
  "ndn.HelloConsumer"
  "ndn.HelloProducer"
  
  "ndn-cxx.nfd.Forwarder"

  "ndn.WifiNetDeviceTransport"
  "WifiNetDevice"

  "YansWifiPhy"
  "YansWifiChannel"
  "InterferenceHelper"
)

# Save the old IFS, set the new one to ':', join, then restore IFS
saved_ifs=$IFS
IFS=":"
component_names="${log_components[*]}"
IFS=$saved_ifs

# Run ns3
NS_LOG="$component_names" ./waf --run="$1" 2> "export.log"