#!/usr/bin/python3

import argparse
import sys
import os

log_components={ 
  "caf.StackHelper": "csh",
  "caf.Context": "cc",

  "ndn.StackHelper": "nsh",
  "ndn.FibHelper": "nfh",

  "ndn.Consumer": "nc",
  "ndn.Producer": "np",
  "ndn.AlertConsumer": "nac",
  "ndn.AlertProducer": "nap",
  "ndn.HelloConsumer": "nhc",
  "ndn.HelloProducer": "nhp",

  "ndn-cxx.nfd.Forwarder": "nfd",

  "ndn.WifiNetDeviceTransport": "wndt",
  "WifiNetDevice": "wnd",

  "YansWifiPhy": "ywp",
  "YansWifiChannel": "ywc",
  "InterferenceHelper": "ih",
}

# 1. Setup Argument Parser
parser = argparse.ArgumentParser()
parser.add_argument('components', nargs='+', choices=list(log_components.values()), help='Components to filter')

args = parser.parse_args()

filename = "export.log"
components = set(args.components)

if not os.path.exists(filename):
    print(f"Error: File '{filename}' not found.")
    sys.exit(1)

filtered_lines = []

# 2. Read and Filter
# The log format is usually: +[Time]s [NodeID] [Class]:[Function]
try:
    with open(filename, 'r') as file, open('extract.log','w') as tee:
        for line in file:
            parts = line.split()
            # Check if line has enough parts (minimum 3) and the third part is contains class:function
            if len(parts) > 2:
                class_name = parts[2].split(':')[0]
                short_hand = log_components[class_name]
                if short_hand in components:
                    tee.write(line)
                    print(line, end='')
except Exception as e:
    print(f"An error occurred: {e}")