#!/bin/bash

# Path to your SUMO tools
scene_dir="sumo/$1"

if [[ ! -f $TRACE_EXPORTER ]]; then
    echo "$TRACE_EXPORTER file doesn't exists"
    echo "export \$TRACE_EXPORTER in your .bashrc"
    exit 1
fi

if [[ ! -d "$scene_dir" ]]; then
    echo "$scene_dir directory doesn't exists"
    exit 1
fi

echo "Running simulation"
echo "-----------------------------------"

cd "$scene_dir"

# Run SUMO
sumo -c "$1.sumocfg" --fcd-output="fcd-trace.xml"

# Check if SUMO ran successfully
if [ $? -ne 0 ]; then
	echo "Error: SUMO simulation failed."
	exit
fi

# Convert the FCD trace to ns2 mobility trace
python3 "$TRACE_EXPORTER" --fcd-input="fcd-trace.xml" --ns2mobility-output="$1.tcl"

# Remove fcd-trace.xml file and move .tcl file into trace directory
rm fcd-trace.xml
mv "$1.tcl" ../../trace/

echo "-----------------------------------"
echo "Simulation completed."